version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: loginTest
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loginTest"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--databases"
      - "2"
      - "--requirepass"
      - "example"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "example", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
      
volumes:
  redis-data:
    driver: local